// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInWindsurf
{
    internal sealed partial class Vsix
    {
        public const string Id = "a3f7c1d2-b4e5-4f6a-9b0c-1d2e3f4a5b6c";
        public const string Name = "Open in Windsurf";
        public const string Description = "Adds a menu command that lets you open any solution, project, folder and file in Windsurf.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "";
        public const string Tags = "windsurf";
    }
}
