// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the VSIX Synchronizer.
//     Do not edit manually - regenerate by rebuilding the project.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace OpenInWindsurf
{
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e";
        public static readonly Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenInWindsurfCmdSetString = "c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f";
        public static readonly Guid guidOpenInWindsurfCmdSet = new Guid(guidOpenInWindsurfCmdSetString);

        public const string guidOpenCurrentInWindsurfCmdSetString = "d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f7a";
        public static readonly Guid guidOpenCurrentInWindsurfCmdSet = new Guid(guidOpenCurrentInWindsurfCmdSetString);
    }

    internal sealed partial class PackageIds
    {
        public const int OpenInWindsurf = 0x0100;
        public const int OpenCurrentInWindsurf = 0x0101;
    }
}
